# SpringBootを構築
version: '3.3'
services:
    app:
        build:
            context: .
            args:
                - JAR_FILE=springapi-0.0.1-SNAPSHOT.jar
        ports:
            - '8081:8080'
